theme: jekyll-theme-modernist
timezone: America/New_York

title: Grailville Wetlands Project
e-mail: belkinsa@ubuntu.com
twitter: https://twitter.com/senseopenness

collections:
  articles:
    output: true
permalink: /:path/

